import { DateTime } from "luxon";
import type { Projection, Task } from "../types.js";
import type { Config } from "./config.js";
import { taskGrossMin, collectIntervals } from "./replay.js";
import { formatMin } from "./time.js";
import { board, quadrant, report, windowFor } from "./report.js";

// A self-contained HTML companion to agent-board.md. The agent board stays the
// agent/memory-readable source of truth; this is the rich visual view — an
// interactive important × urgent quadrant map, a colour-coded kanban, a project
// rollup, and the WBS tree — in one file you open in a browser. It is
// regenerated by the same engine hook after every event.

const COLS = ["todo", "doing", "paused", "blocked", "done"] as const;
const ic = (name: string) => `<i class="bi bi-${name}"></i>`;
const COL_TITLES: Record<(typeof COLS)[number], string> = {
  todo: `${ic("list-task")} To Do`,
  doing: `${ic("hammer")} Doing`,
  paused: `${ic("pause-circle")} Paused`,
  blocked: `${ic("slash-circle")} Blocked`,
  done: `${ic("check-circle")} Done`,
};

// A/B/C/D class + colour for each Eisenhower quadrant.
const CLASS: Record<string, { k: string; label: string; color: string }> = {
  Q1: { k: "A", label: "do first", color: "#c96a6a" }, // dusty red
  Q2: { k: "B", label: "schedule", color: "#5a9b7d" }, // sage
  Q3: { k: "C", label: "delegate", color: "#c2a15c" }, // muted gold
  Q4: { k: "D", label: "eliminate", color: "#9aa1a9" }, // grey
};
const cls = (t: Task) => CLASS[quadrant(t)];

function esc(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

function zoneOf(config: Config): string | undefined {
  return !config.timezone || config.timezone === "system" ? undefined : config.timezone;
}
function toDT(iso: string, config: Config): DateTime {
  const z = zoneOf(config);
  const d = DateTime.fromISO(iso);
  return z ? d.setZone(z) : d;
}

function progressPct(t: Task, nowISO: string): number | undefined {
  if (!t.estMin) return undefined;
  return Math.min(100, Math.round((taskGrossMin(t, nowISO) / t.estMin) * 100));
}

function deadlineHtml(t: Task, nowMs: number, config: Config): string {
  if (!t.deadline) return "";
  const z = zoneOf(config);
  const dl = DateTime.fromISO(t.deadline, z ? { zone: z } : {}).endOf("day").toMillis();
  const days = (dl - nowMs) / 86400000;
  const overdue = t.status !== "done" && days < 0;
  const urgent = t.status !== "done" && days >= 0 && days <= 2;
  const icon = ic(overdue ? "exclamation-triangle" : urgent ? "alarm" : "calendar-event");
  const kind = overdue ? "overdue" : urgent ? "due" : "sched";
  return `<span class="dl ${kind}">${icon} ${esc(t.deadline)}</span>`;
}

// ---- interactive important × urgent quadrant map (ECharts via CDN) ----

// Embed a JS data literal safely inside a <script> (guard against </script>).
function jsonInline(v: unknown): string {
  return JSON.stringify(v).replace(/</g, "\\u003c").replace(/-->/g, "--\\u003e");
}

function scatter(p: Projection, nowISO: string, project?: string): string {
  const nowMs = Date.parse(nowISO);
  const pts: {
    title: string; u: boolean; i: boolean; k: string; color: string; project: string;
    done: boolean; created: number; last: number;
  }[] = [];
  for (const id of p.order) {
    const t = p.tasks.get(id)!;
    if (t.archived) continue;
    if (project && t.project !== project) continue;
    const c = cls(t);
    const created = Date.parse(t.createdAt);
    const last = t.spans.length ? Math.max(...t.spans.map((s) => Date.parse(s.end ?? nowISO))) : created;
    pts.push({ title: t.title, u: t.urgent, i: t.important, k: c.k, color: c.color, project: t.project ?? "", done: t.status === "done", created, last });
  }
  if (pts.length === 0) return "";

  return `
  <section class="panel">
    <div class="panel-head">
      <h2>Priority map <span class="sub">· important × urgent</span></h2>
      <select id="scatter-filter" class="filter" aria-label="which tasks to plot">
        <option value="current">Currently active</option>
        <option value="all">All tasks</option>
        <option value="recent">Recent · last 30 days</option>
      </select>
    </div>
    <p class="sub">One dot per task, placed by important (y) and urgent (x). Done tasks are faded. Hover for details.</p>
    <div id="scatter" class="chart"></div>
    <script>
    (function(){
      var pts = ${jsonInline(pts)};
      var now = ${nowMs}, cutoff = now - 30*86400000;
      var el = document.getElementById('scatter');
      if(!el || typeof echarts === 'undefined') return;
      var dark = matchMedia('(prefers-color-scheme: dark)').matches;
      var fg = dark ? '#9a9a95' : '#6b6b66';
      var C = { A:'#c96a6a', B:'#5a9b7d', C:'#c2a15c', D:'#9aa1a9' };
      var chart = echarts.init(el, null, { renderer:'svg' });
      var M = 1.7;
      var lbl = function(v){ return v > 0.5 ? 'yes' : (v < -0.5 ? 'no' : ''); };
      function pick(mode){
        return pts.filter(function(pt){
          if(mode === 'all') return true;
          if(mode === 'recent') return pt.created >= cutoff || pt.last >= cutoff;
          return !pt.done;
        });
      }
      function toData(list){
        return list.map(function(pt, idx){
          var jx = (((idx % 3) - 1) * 0.2), jy = (((Math.floor(idx / 3) % 3) - 1) * 0.2);
          return { value:[(pt.u ? 1 : -1) + jx, (pt.i ? 1 : -1) + jy], pt:pt,
            itemStyle:{ color:pt.color, borderColor:dark?'#161617':'#fff', borderWidth:1.5, opacity: pt.done ? 0.4 : 0.92 } };
        });
      }
      var band = function(name, col, x0, y0, x1, y1, pos){
        return [{ name:name, xAxis:x0, yAxis:y0, itemStyle:{ color:col, opacity:0.08 }, label:{ show:true, color:col, fontWeight:700, position:pos, fontSize:11 } }, { xAxis:x1, yAxis:y1 }];
      };
      chart.setOption({
        grid:{ left:64, right:26, top:22, bottom:52 },
        tooltip:{ trigger:'item', formatter:function(o){ var q=o.data.pt; return '<b>'+q.title+'</b><br/>category '+q.k+' · important: '+(q.i?'yes':'no')+' · urgent: '+(q.u?'yes':'no')+(q.done?' · done':'')+(q.project?'<br/>project '+q.project:''); } },
        xAxis:{ name:'urgent →', nameLocation:'middle', nameGap:30, min:-M, max:M, interval:1, axisLabel:{ color:fg, formatter:lbl }, nameTextStyle:{ color:fg, fontWeight:600 }, splitLine:{ show:false } },
        yAxis:{ name:'important →', nameLocation:'middle', nameGap:22, min:-M, max:M, interval:1, axisLabel:{ color:fg, formatter:lbl }, nameTextStyle:{ color:fg, fontWeight:600 }, splitLine:{ show:false } },
        series:[{
          type:'scatter', symbolSize:20, data:toData(pick('current')), emphasis:{ scale:1.35 },
          markArea:{ silent:true, data:[
            band('B · important', C.B, -M, 0, 0, M, 'insideTopLeft'),
            band('A · do first', C.A, 0, 0, M, M, 'insideTopRight'),
            band('D · neither', C.D, -M, -M, 0, 0, 'insideBottomLeft'),
            band('C · urgent', C.C, 0, -M, M, 0, 'insideBottomRight')
          ] },
          markLine:{ silent:true, symbol:'none', label:{ show:false }, lineStyle:{ color:fg, width:1.25, opacity:0.55 }, data:[ { xAxis:0 }, { yAxis:0 } ] }
        }]
      });
      var sel = document.getElementById('scatter-filter');
      if(sel) sel.addEventListener('change', function(){ chart.setOption({ series:[{ data: toData(pick(sel.value)) }] }); });
      window.addEventListener('resize', function(){ chart.resize(); });
    })();
    </script>
  </section>`;
}

// ---- kanban ----

function kanbanCard(t: Task, nowISO: string, nowMs: number, config: Config, showProject: boolean): string {
  const c = cls(t);
  const pct = progressPct(t, nowISO);
  const logged = taskGrossMin(t, nowISO);
  const est = t.estMin ? `<span class="est" title="estimate to finish">${ic("clock")} ${formatMin(t.estMin)}</span>` : "";
  const left = t.estMin && t.status !== "done" ? ` · ${formatMin(Math.max(0, t.estMin - logged))} left` : "";
  const bar =
    pct !== undefined && t.status !== "done"
      ? `<div class="bar"><span style="width:${pct}%;background:${c.color}"></span></div><span class="pct">${pct}%${left}</span>`
      : "";
  const proj = showProject && t.project ? `<span class="proj">${esc(t.project)}</span>` : "";
  const flags = [t.important ? "important" : "", t.urgent ? "urgent" : ""].filter(Boolean).join(" · ") || "—";
  return `
      <div class="card" style="--c:${c.color}">
        <div class="card-top"><span class="badge" title="${c.k} · ${c.label}">${c.k}</span><code>${esc(t.id)}</code></div>
        <div class="ct">${esc(t.title)}</div>
        <div class="meta"><span class="score">${flags}</span>${est}${proj}${deadlineHtml(t, nowMs, config)}</div>
        ${bar ? `<div class="barrow">${bar}</div>` : ""}
      </div>`;
}

function kanban(p: Projection, nowISO: string, nowMs: number, config: Config, project?: string): string {
  const cols = board(p, project);
  const shown = COLS.filter((c) => ["todo", "doing", "done"].includes(c) || cols[c].length > 0);
  const columns = shown
    .map((col) => {
      const cards = cols[col].map((it) => kanbanCard(p.tasks.get(it.id)!, nowISO, nowMs, config, !project)).join("");
      return `
    <div class="col">
      <h3>${COL_TITLES[col]} <span class="count">${cols[col].length}</span></h3>
      <div class="col-body">${cards || '<div class="empty">—</div>'}</div>
    </div>`;
    })
    .join("");
  return `<section class="panel"><h2>Board</h2><div class="kanban">${columns}</div></section>`;
}

// ---- project rollup ----

function rollup(p: Projection, nowISO: string, project?: string): string {
  const rows = new Map<string, { est: number; logged: number }>();
  let anyEst = false;
  for (const id of p.order) {
    const t = p.tasks.get(id)!;
    if (t.archived) continue;
    if (project && t.project !== project) continue;
    const key = t.project ?? "(none)";
    const r = rows.get(key) ?? { est: 0, logged: 0 };
    if (t.estMin) (r.est += t.estMin), (anyEst = true);
    r.logged += taskGrossMin(t, nowISO);
    rows.set(key, r);
  }
  if (rows.size === 0 || !anyEst) return "";
  const entries = [...rows.entries()].sort((a, b) => b[1].est - a[1].est);
  const row = (label: string, est: number, logged: number, bold = false) => {
    const pct = est > 0 ? Math.min(100, Math.round((logged / est) * 100)) : 0;
    const rem = Math.max(0, est - logged);
    return `<tr${bold ? ' class="total"' : ""}><td>${esc(label)}</td><td>${est ? formatMin(est) : "—"}</td><td>${formatMin(logged)}</td><td>${est ? formatMin(rem) : "—"}</td><td><div class="bar"><span style="width:${pct}%"></span></div> ${pct}%</td></tr>`;
  };
  let est = 0,
    logged = 0;
  const body = entries.map(([k, v]) => ((est += v.est), (logged += v.logged), row(k, v.est, v.logged))).join("");
  const total = entries.length > 1 ? row("all", est, logged, true) : "";
  return `<section class="panel"><h2>Project rollup</h2><table class="tbl"><thead><tr><th>Project</th><th>Est</th><th>Logged</th><th>Rem</th><th>Progress</th></tr></thead><tbody>${body}${total}</tbody></table></section>`;
}

// ---- Work Breakdown calendar (Gantt) ----

// The rolling 3-week window (last · this · next) used to scope the timeline.
function threeWeek(nowISO: string, config: Config): { start: number; end: number }[] {
  const cur = toDT(nowISO, config).startOf("week");
  const mk = (d: DateTime) => ({ start: d.toMillis(), end: d.plus({ weeks: 1 }).toMillis() });
  return [mk(cur.minus({ weeks: 1 })), mk(cur), mk(cur.plus({ weeks: 1 }))];
}

// The Work Breakdown as a calendar timeline (ECharts Gantt): each task is a row
// in WBS order (children indented), work spans are bars over real calendar
// dates, deadlines are diamonds, and a dashed line marks "today".
function gantt(p: Projection, config: Config, nowISO: string, project?: string): string {
  const weeks = threeWeek(nowISO, config);
  const nowMs = Date.parse(nowISO);
  const lo = weeks[0].start,
    hi = weeks[2].end;
  const inScope = new Set<string>();
  for (const id of p.order) {
    const t = p.tasks.get(id)!;
    if (t.archived) continue;
    if (project && t.project !== project) continue;
    const logged = collectIntervals([t], nowISO, lo, hi).length > 0;
    if (t.status !== "done" || logged) inScope.add(id);
  }
  if (inScope.size === 0) return "";
  for (const id of [...inScope]) {
    let cur = p.tasks.get(id)?.parent;
    while (cur && p.tasks.has(cur) && !inScope.has(cur) && !p.tasks.get(cur)!.archived) {
      inScope.add(cur);
      cur = p.tasks.get(cur)?.parent;
    }
  }
  // Row order: DFS (roots then children), tracking depth for indentation.
  const children = new Map<string, string[]>();
  const roots: string[] = [];
  for (const id of p.order) {
    if (!inScope.has(id)) continue;
    const t = p.tasks.get(id)!;
    if (t.parent && inScope.has(t.parent)) (children.get(t.parent) ?? children.set(t.parent, []).get(t.parent)!).push(id);
    else roots.push(id);
  }
  const order: { id: string; depth: number }[] = [];
  const walk = (id: string, depth: number) => {
    order.push({ id, depth });
    for (const c of children.get(id) ?? []) walk(c, depth + 1);
  };
  for (const r of roots) walk(r, 0);

  const z = zoneOf(config);
  const open = [...p.periods.values()].find((pr) => pr.open);
  const capPerDay = open?.capacityHoursPerDay ?? config.capacityHoursPerDay; // focus-hours/day
  const DAY = 86400000;
  const fmtG = (ms: number) => toDT(new Date(ms).toISOString(), config).toFormat("yyyy-LL-dd HH:mm:ss");
  const startOfToday = toDT(nowISO, config).startOf("day").toMillis();

  // One Frappe-Gantt task per row = its PLANNED timespan; progress fill = logged/est.
  const tasks = order.map(({ id, depth }) => {
    const t = p.tasks.get(id)!;
    const c = cls(t);
    const logged = taskGrossMin(t, nowISO);
    // Planned window: estimate -> calendar days at capacity, backward-scheduled
    // from the deadline (else forward from today). Fall back to logged extent
    // or a 1-day block anchored at the deadline/today.
    let pStart: number, pEnd: number;
    if (t.estMin) {
      const durMs = Math.max(0.5 * DAY, (t.estMin / (capPerDay * 60)) * DAY);
      if (t.deadline) {
        pEnd = DateTime.fromISO(t.deadline, z ? { zone: z } : {}).endOf("day").toMillis();
        pStart = pEnd - durMs;
      } else {
        pStart = startOfToday;
        pEnd = pStart + durMs;
      }
    } else if (t.spans.length) {
      pStart = Math.min(...t.spans.map((s) => Date.parse(s.start)));
      pEnd = Math.max(...t.spans.map((s) => Date.parse(s.end ?? new Date(nowMs).toISOString())));
    } else {
      const anchor = t.deadline ? DateTime.fromISO(t.deadline, z ? { zone: z } : {}).startOf("day").toMillis() : startOfToday;
      pStart = anchor;
      pEnd = anchor + DAY;
    }
    if (pEnd <= pStart) pEnd = pStart + 0.5 * DAY;
    const progress = t.estMin ? Math.min(100, Math.round((logged / t.estMin) * 100)) : t.status === "done" ? 100 : 0;
    const over = !!t.deadline && t.status !== "done" && DateTime.fromISO(t.deadline!, z ? { zone: z } : {}).endOf("day").toMillis() < nowMs;
    return {
      id: t.id,
      name: "  ".repeat(depth) + (depth ? "└ " : "") + t.title,
      start: fmtG(pStart),
      end: fmtG(pEnd),
      progress,
      custom_class: `cat-${c.k}${over ? "-od" : ""}`, // single token — Frappe classList.add rejects spaces
      _details:
        `${esc(t.title)} · ${c.k} ${c.label}` +
        `<br/>${t.status}${t.project ? " · " + esc(t.project) : ""}` +
        `<br/>est ${t.estMin ? formatMin(t.estMin) : "—"} · logged ${formatMin(logged)}` +
        (t.estMin ? ` · ${formatMin(Math.max(0, t.estMin - logged))} left (${progress}%)` : "") +
        (t.deadline ? `<br/>deadline ${t.deadline}${over ? ` ${ic("exclamation-triangle")} overdue` : ""}` : ""),
    };
  });

  // Scroll the initial view to the earliest task so bars are on-screen (start
  // strings sort chronologically). Fall back to today.
  const scrollTo = tasks.length ? tasks.map((t) => t.start).sort()[0].slice(0, 10) : "today";

  return `
  <section class="panel">
    <h2>Work Breakdown <span class="sub">· calendar timeline</span></h2>
    <p class="sub">One bar per task = the planned timespan (estimate scheduled to its deadline); the fill shows % logged. Switch Day / Week / Month, jump to Today, hover a bar for details.</p>
    <div class="gantt-wrap"><div id="gantt"></div></div>
    <script>
    (function(){
      var tasks = ${jsonInline(tasks)};
      var el = document.getElementById('gantt');
      if(!el) return;
      if(typeof Gantt === 'undefined'){ el.innerHTML = '<p class="sub">Gantt library failed to load (needs a connection).</p>'; return; }
      var detail = {}; tasks.forEach(function(t){ detail[t.id] = t._details; });
      try {
        new Gantt(el, tasks, {
          view_mode: 'Week',
          view_mode_select: true,
          today_button: true,
          scroll_to: ${JSON.stringify(scrollTo)},
          readonly: true,
          popup_on: 'hover',
          bar_height: 26,
          padding: 18,
          show_expected_progress: true,
          holidays: { 'var(--g-weekend-highlight-color)': 'weekend' },
          popup: function(ctx){
            try {
              var id = (ctx && ctx.task && ctx.task.id) || (ctx && ctx.id);
              var html = detail[id];
              if (ctx && ctx.set_title) { ctx.set_title(''); ctx.set_details(html); return; }
              return html;
            } catch(e){ return; }
          }
        });
      } catch(err){ el.innerHTML = '<p class="sub">Could not render the timeline: ' + (err && err.message ? err.message : err) + '</p>'; }
    })();
    </script>
  </section>`;
}

// ---- metrics, per-axis splits, sprint ----

/** Gross minutes on a task within [lo, hi). */
function grossIn(t: Task, nowISO: string, lo: number, hi: number): number {
  let s = 0;
  for (const iv of collectIntervals([t], nowISO, lo, hi)) s += (iv.end - iv.start) / 60000;
  return s;
}

function metricsSection(p: Projection, config: Config, nowISO: string): string {
  const week = report(p, config, nowISO, { window: "week", by: "project" });
  const today = report(p, config, nowISO, { window: "today", by: "project" });
  if (week.grossMin === 0 && today.grossMin === 0) {
    return `<section class="panel"><h2>Metrics</h2><p class="sub">No time logged yet — start a task and it'll show up here.</p></section>`;
  }
  const z = zoneOf(config);
  const nowMs = Date.parse(nowISO);
  const win = windowFor("week", p, nowISO, config);
  const wq = report(p, config, nowISO, { window: "week", by: "quadrant" });
  const qm = new Map(wq.distribution);
  const g = wq.grossMin;
  const pctOf = (min: number) => (g > 0 ? Math.round((min / g) * 100) : 0);
  const focus = pctOf((qm.get("Q1") ?? 0) + (qm.get("Q2") ?? 0)); // A+B: important work
  const deep = pctOf(qm.get("Q2") ?? 0); // B: important, not urgent
  const fire = pctOf(qm.get("Q1") ?? 0); // A: firefighting

  // Delivered this week: tasks finished (last span ends in the window) + time on them.
  let doneN = 0,
    doneMin = 0;
  for (const t of p.tasks.values()) {
    if (t.archived || t.status !== "done" || t.spans.length === 0) continue;
    const lastEnd = Math.max(...t.spans.map((s) => Date.parse(s.end ?? nowISO)));
    if (lastEnd >= win.start && lastEnd <= win.end) {
      doneN++;
      doneMin += grossIn(t, nowISO, win.start, win.end);
    }
  }
  // Estimate accuracy: median actual/estimate over finished, estimated tasks.
  const ratios = week.eva.map((e) => e.ratio).sort((a, b) => a - b);
  const acc = ratios.length ? ratios[Math.floor(ratios.length / 2)] : undefined;
  const accStr = acc === undefined ? "—" : Math.abs(acc - 1) <= 0.1 ? "on target" : `${acc.toFixed(1)}×`;
  // At risk: open tasks already past their deadline.
  let atRisk = 0;
  for (const t of p.tasks.values()) {
    if (t.archived || t.status === "done" || !t.deadline) continue;
    if (DateTime.fromISO(t.deadline, z ? { zone: z } : {}).endOf("day").toMillis() < nowMs) atRisk++;
  }

  const stat = (label: string, val: string, sub: string, accent?: string) =>
    `<div class="stat"><div class="sv"${accent ? ` style="color:${accent}"` : ""}>${val}</div><div class="sl">${label}</div><div class="ss">${sub}</div></div>`;

  const projRows = week.distribution
    .map(([k, v]) => {
      const pct = Math.round((v / week.grossMin) * 100);
      return `<tr><td>${esc(k)}</td><td>${formatMin(v)}</td><td><div class="bar"><span style="width:${pct}%"></span></div> ${pct}%</td></tr>`;
    })
    .join("");

  return `<section class="panel"><h2>Metrics <span class="sub">· ${esc(week.win.label)}</span></h2>
    <p class="sub">You spent <b>${focus}%</b> of ${formatMin(g)} on important work — ${deep}% deep (B), ${fire}% firefighting (A)${acc !== undefined ? `. Estimates ran <b>${accStr}</b>` : ""}${atRisk ? `. <b style="color:#c96a6a">${atRisk}</b> task${atRisk === 1 ? "" : "s"} overdue` : ""}.</p>
    <div class="stats">
      ${stat("Focus", focus + "%", "on important work (A+B)", focus >= 60 ? "#5a9b7d" : undefined)}
      ${stat("Deep work", deep + "%", "important, not urgent (B)", "#5a9b7d")}
      ${stat("Firefighting", fire + "%", "urgent + important (A)", fire >= 30 ? "#c96a6a" : undefined)}
      ${stat("Delivered", String(doneN), `${doneN === 1 ? "task" : "tasks"} · ${formatMin(doneMin)}`)}
      ${stat("Est. accuracy", accStr, "actual vs estimate")}
      ${stat("At risk", String(atRisk), "past deadline", atRisk ? "#c96a6a" : undefined)}
    </div>
    <table class="tbl"><thead><tr><th>Project</th><th>Time</th><th>Share</th></tr></thead><tbody>${projRows}</tbody></table>
  </section>`;
}

// Where time mostly goes: logged time this week split across the 4 categories.
const CAT_META: Record<string, { k: string; label: string; color: string }> = {
  Q1: { k: "A", label: "important + urgent", color: "#c96a6a" },
  Q2: { k: "B", label: "important, not urgent", color: "#5a9b7d" },
  Q3: { k: "C", label: "urgent, not important", color: "#c2a15c" },
  Q4: { k: "D", label: "neither", color: "#9aa1a9" },
};
function categorySection(p: Projection, config: Config, nowISO: string, project?: string): string {
  const win = windowFor("week", p, nowISO, config);
  const m = new Map<string, number>();
  let total = 0;
  for (const id of p.order) {
    const t = p.tasks.get(id)!;
    if (t.archived) continue;
    if (project && t.project !== project) continue;
    const g = grossIn(t, nowISO, win.start, win.end);
    if (g <= 0) continue;
    const q = quadrant(t);
    m.set(q, (m.get(q) ?? 0) + g);
    total += g;
  }
  if (total <= 0) return "";
  const rows = (["Q1", "Q2", "Q3", "Q4"] as const)
    .map((q) => ({ q, v: m.get(q) ?? 0 }))
    .sort((a, b) => b.v - a.v)
    .filter((r) => r.v > 0)
    .map((r) => {
      const meta = CAT_META[r.q];
      const pct = Math.round((r.v / total) * 100);
      return `<tr><td><span class="badge sm" style="--c:${meta.color}">${meta.k}</span> ${meta.label}</td><td>${formatMin(r.v)}</td><td><div class="bar"><span style="width:${pct}%;background:${meta.color}"></span></div> ${pct}%</td></tr>`;
    })
    .join("");
  return `<section class="panel"><h2>Time by category <span class="sub">· ${esc(win.label)}</span></h2>
    <p class="sub">Where your time actually went, by Eisenhower category.</p>
    <table class="tbl"><thead><tr><th>Category</th><th>Time</th><th>Share</th></tr></thead><tbody>${rows}</tbody></table></section>`;
}

function sprintSection(p: Projection, config: Config, nowISO: string): string {
  const open = [...p.periods.values()].find((pr) => pr.open);
  if (!open) return "";
  const r = report(p, config, nowISO, { window: "sprint", by: "project" });
  if (!r.onTrack) return "";
  const { remainingMin, capacityMin, verdict } = r.onTrack;
  const pct = capacityMin > 0 ? Math.min(100, Math.round((remainingMin / capacityMin) * 100)) : 0;
  const risk = verdict !== "on track";
  return `<section class="panel"><h2>Sprint <span class="sub">· ${esc(open.id)} (${open.start} → ${open.end})</span></h2>
    <p class="sub">${formatMin(remainingMin)} remaining vs ${formatMin(capacityMin)} capacity</p>
    <div class="barrow"><div class="bar"><span style="width:${pct}%;background:${risk ? "#c96a6a" : "#5a9b7d"}"></span></div><span class="pct">${esc(verdict)}</span></div>
  </section>`;
}

// ---- page ----

export function boardHtml(p: Projection, config: Config, nowISO: string, project?: string): string {
  const nowMs = Date.parse(nowISO);
  const total = p.order.filter((id) => {
    const t = p.tasks.get(id)!;
    return !t.archived && (!project || t.project === project);
  }).length;
  const doing = [...p.tasks.values()].filter((t) => !t.archived && t.status === "doing" && (!project || t.project === project)).length;
  const generated = toDT(nowISO, config).toFormat("yyyy-LL-dd HH:mm");
  const legend = Object.values(CLASS)
    .map((c) => `<span class="lg"><span class="sw" style="background:${c.color}"></span>${c.k} · ${c.label}</span>`)
    .join("");

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>Tempo Board</title>
<script src="https://cdn.jsdelivr.net/npm/echarts@5.5.1/dist/echarts.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/frappe-gantt@1.2.2/dist/frappe-gantt.css"/>
<script src="https://cdn.jsdelivr.net/npm/frappe-gantt@1.2.2/dist/frappe-gantt.umd.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"/>
<style>
/* Clean Minimalism: soft off-white ground, hairline borders, whitespace over
   rules, muted accents. Calm, focused, premium. */
:root{
  --bg:#f5f5f3;--panel:#fdfdfc;--ink:#1a1a19;--muted:#6b6b66;--faint:#9b9b95;
  --line:#ececea;--hair:#f1f1ef;--radius:14px;
}
@media (prefers-color-scheme:dark){:root{
  --bg:#0e0e0f;--panel:#161617;--ink:#f2f2f0;--muted:#9a9a95;--faint:#6a6a66;
  --line:#232324;--hair:#1d1d1e;
}}
*{box-sizing:border-box}
body{margin:0;font:14px/1.65 ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;background:var(--bg);color:var(--ink);-webkit-font-smoothing:antialiased;text-rendering:optimizeLegibility}
.wrap{max-width:1400px;margin:0 auto;padding:64px 40px 112px}
header{margin-bottom:8px}
header h1{margin:0 0 10px;font-size:26px;font-weight:600;letter-spacing:-0.02em}
.status{color:var(--muted);font-size:13.5px}
.status b{color:var(--ink);font-weight:600}
.legend{display:flex;flex-wrap:wrap;gap:20px;margin:20px 0 0;font-size:12px;color:var(--muted)}
.lg{display:inline-flex;align-items:center;gap:8px}
.sw{width:8px;height:8px;border-radius:50%;display:inline-block}
.panel{background:var(--panel);border:1px solid var(--line);border-radius:var(--radius);padding:32px 34px;margin:24px 0}
.panel h2{margin:0;font-size:12px;font-weight:600;text-transform:uppercase;letter-spacing:0.09em;color:var(--muted)}
.panel h2 .sub{text-transform:none;letter-spacing:0;font-weight:400;color:var(--faint)}
.panel-head{display:flex;justify-content:space-between;align-items:center;gap:12px;flex-wrap:wrap}
.filter{appearance:none;background:var(--bg);color:var(--ink);border:1px solid var(--line);border-radius:8px;padding:6px 30px 6px 12px;font:inherit;font-size:12.5px;cursor:pointer;
  background-image:linear-gradient(45deg,transparent 50%,var(--faint) 50%),linear-gradient(135deg,var(--faint) 50%,transparent 50%);
  background-position:calc(100% - 15px) 52%,calc(100% - 10px) 52%;background-size:5px 5px,5px 5px;background-repeat:no-repeat}
.filter:hover{border-color:var(--muted)}
.sub{color:var(--faint);font-size:12.5px;margin:8px 0 24px;font-weight:400}
.chart{width:100%;height:440px;margin-top:8px}
/* Frappe Gantt — themed to Clean Minimalism via its CSS variables (inherit from .gantt-wrap) */
.gantt-wrap{margin-top:20px;overflow-x:auto;
  --g-header-background:var(--panel);--g-row-color:transparent;--g-row-border-color:var(--hair);
  --g-border-color:var(--line);--g-tick-color:var(--hair);--g-tick-color-thick:var(--line);
  --g-text-dark:var(--ink);--g-text-muted:var(--muted);--g-text-light:#fff;
  --g-bar-color:var(--hair);--g-bar-border:var(--line);--g-progress-color:var(--muted);
  --g-expected-progress:var(--faint);--g-today-highlight:var(--faint);
  --g-weekend-highlight-color:rgba(0,0,0,0.035);--g-actions-background:var(--panel);--g-popup-actions:var(--muted)}
@media (prefers-color-scheme:dark){.gantt-wrap{--g-weekend-highlight-color:rgba(255,255,255,0.035)}}
/* Each bar = a faint category-tinted track (visible even at 0% progress) with a
   solid category fill for the logged %. */
.gantt-wrap .bar{stroke-width:1px}
.gantt-wrap .bar-wrapper[class*="cat-A"] .bar{fill:#c96a6a;fill-opacity:.16;stroke:#c96a6a;stroke-opacity:.55}
.gantt-wrap .bar-wrapper[class*="cat-A"] .bar-progress{fill:#c96a6a}
.gantt-wrap .bar-wrapper[class*="cat-B"] .bar{fill:#5a9b7d;fill-opacity:.16;stroke:#5a9b7d;stroke-opacity:.55}
.gantt-wrap .bar-wrapper[class*="cat-B"] .bar-progress{fill:#5a9b7d}
.gantt-wrap .bar-wrapper[class*="cat-C"] .bar{fill:#c2a15c;fill-opacity:.16;stroke:#c2a15c;stroke-opacity:.55}
.gantt-wrap .bar-wrapper[class*="cat-C"] .bar-progress{fill:#c2a15c}
.gantt-wrap .bar-wrapper[class*="cat-D"] .bar{fill:#9aa1a9;fill-opacity:.2;stroke:#9aa1a9;stroke-opacity:.55}
.gantt-wrap .bar-wrapper[class*="cat-D"] .bar-progress{fill:#9aa1a9}
.gantt-wrap .bar-wrapper[class*="-od"] .bar{stroke:#c96a6a;stroke-width:1.75px;stroke-opacity:1}
.gantt-wrap .bar-label{fill:var(--ink);font-size:12px}
.gantt-wrap .bar-label.big{fill:var(--muted)}
.stats{display:flex;flex-wrap:wrap;gap:40px;margin:22px 0 6px}
.stat .sv{font-size:23px;font-weight:600;letter-spacing:-0.02em;font-variant-numeric:tabular-nums}
.stat .sl{font-size:11px;color:var(--faint);text-transform:uppercase;letter-spacing:0.06em;margin-top:4px}
.stat .ss{font-size:11.5px;color:var(--muted);margin-top:3px}
.mix{display:flex;flex-wrap:wrap;gap:18px;margin:16px 0 4px;font-size:12.5px;color:var(--muted)}
.mix .mi{display:inline-flex;align-items:center;gap:7px}
.mix .mi::before{content:"";width:8px;height:8px;border-radius:50%;background:var(--c)}
/* single row: all status columns stay on one line (scrolls only if they truly
   can't fit), so Done never wraps to a new row */
.kanban{display:grid;grid-auto-flow:column;grid-auto-columns:minmax(200px,1fr);gap:20px;margin-top:26px;overflow-x:auto;align-items:start}
.col{min-width:0;display:flex;flex-direction:column}
/* a long column (e.g. Done) scrolls inside its own box instead of stretching the page */
.col-body{overflow-y:auto;max-height:min(64vh,620px);padding-right:4px;scrollbar-width:thin}
.col-body::-webkit-scrollbar{width:7px}
.col-body::-webkit-scrollbar-thumb{background:var(--line);border-radius:6px}
.col h3{margin:0 0 14px;font-size:11px;font-weight:600;text-transform:uppercase;letter-spacing:0.07em;color:var(--faint);position:sticky;top:0}
.bi{vertical-align:-0.12em;line-height:1}
.dl .bi,.est .bi{font-size:0.95em}
.col .count{color:var(--faint);font-weight:400;margin-left:5px}
.card{border:1px solid var(--hair);border-radius:11px;padding:15px 16px;margin-bottom:12px;background:var(--bg)}
.card-top{display:flex;align-items:center;gap:9px;margin-bottom:6px}
.badge{background:color-mix(in srgb,var(--c,#9aa1a9) 15%,transparent);color:var(--c,#9aa1a9);font-weight:700;font-size:10.5px;width:19px;height:19px;border-radius:6px;display:inline-flex;align-items:center;justify-content:center;flex:0 0 auto}
.badge.sm{width:17px;height:17px;font-size:10px}
.card code,.node code{font-size:11px;color:var(--faint)}
.ct{font-weight:600;margin-bottom:7px;letter-spacing:-0.01em}
.meta{font-size:11.5px;color:var(--muted);display:flex;flex-wrap:wrap;gap:9px;align-items:center}
.score{font-variant-numeric:tabular-nums;font-weight:600;color:var(--ink)}
.proj{color:var(--faint)}
.est{color:var(--muted);font-variant-numeric:tabular-nums}
.dl{border-radius:6px;padding:1px 7px;font-size:11px}
.dl.overdue{background:#c96a6a1f;color:#c96a6a}
.dl.due{background:#c2a15c22;color:#a8863f}
.barrow{display:flex;align-items:center;gap:9px;margin-top:11px}
.bar{flex:1;height:5px;background:var(--hair);border-radius:4px;overflow:hidden}
.bar.mini{width:64px;flex:0 0 64px}
.bar span{display:block;height:100%;background:var(--muted)}
.pct{font-size:11px;color:var(--faint);font-variant-numeric:tabular-nums}
.empty{color:var(--faint);opacity:.6;font-size:13px}
.tbl{width:100%;border-collapse:collapse;font-size:13px;margin-top:20px}
.tbl th{text-align:left;padding:0 14px 12px;font-size:11px;font-weight:600;text-transform:uppercase;letter-spacing:0.05em;color:var(--faint)}
.tbl td{text-align:left;padding:11px 14px;border-top:1px solid var(--hair)}
.tbl th:not(:first-child),.tbl td:not(:first-child){text-align:right}
.tbl td:last-child,.tbl th:last-child{width:160px}
.tbl .total td{font-weight:700;color:var(--ink)}
.tbl .bar{display:inline-block;width:72px;vertical-align:middle}
.tree,.tree ul{list-style:none;margin:0;padding:0}
.tree{margin-top:22px}
.tree ul{margin-left:22px;padding-left:0}
.tree li{margin:9px 0}
.node{display:flex;flex-wrap:wrap;align-items:center;gap:9px}
.node .nt{font-weight:600;letter-spacing:-0.01em}
.nmeta{font-size:11.5px;color:var(--muted)}
.spark{display:inline-flex;align-items:flex-end;gap:2px;height:15px}
.spark .wk{width:5px;height:15px;background:var(--hair);border-radius:1px;display:inline-flex;align-items:flex-end}
.spark .wk span{width:100%;background:var(--faint);border-radius:1px;min-height:1px}
footer{color:var(--faint);font-size:11px;text-align:center;margin-top:40px}
</style>
</head>
<body>
<div class="wrap">
<header>
  <h1>Tempo Board${project ? ` · ${esc(project)}` : ""}</h1>
  <div class="status"><b>${total}</b> task${total === 1 ? "" : "s"} · <b>${doing}</b> in progress · updated ${generated}</div>
  <div class="legend">${legend}</div>
</header>
${kanban(p, nowISO, nowMs, config, project)}
${rollup(p, nowISO, project)}
${gantt(p, config, nowISO, project)}
${metricsSection(p, config, nowISO)}
${scatter(p, nowISO, project)}
${categorySection(p, config, nowISO, project)}
${sprintSection(p, config, nowISO)}
<footer>Auto-generated after each change — do not edit by hand. agent-board.md holds the same data as text.</footer>
</div>
</body>
</html>
`;
}
