import { DateTime } from "luxon";
import type { Projection, Task } from "../types.js";
import type { Config } from "./config.js";
import { taskGrossMin, collectIntervals } from "./replay.js";
import { formatMin } from "./time.js";
import { board, quadrant, report, windowFor } from "./report.js";

// A self-contained HTML companion to agent-board.md. The agent board stays the
// agent/memory-readable source of truth; this is the rich visual view — an
// interactive importance × urgency scatter, a colour-coded kanban, a project
// rollup, and the WBS tree — in one file you open in a browser. It is
// regenerated by the same engine hook after every event.

const COLS = ["todo", "doing", "paused", "blocked", "done"] as const;
const COL_TITLES: Record<(typeof COLS)[number], string> = {
  todo: "📋 To Do",
  doing: "🔨 Doing",
  paused: "⏸️ Paused",
  blocked: "🚧 Blocked",
  done: "✅ Done",
};

// A/B/C/D class + colour for each Eisenhower quadrant.
const CLASS: Record<string, { k: string; label: string; color: string }> = {
  Q1: { k: "A", label: "do first", color: "#c96a6a" }, // dusty red
  Q2: { k: "B", label: "schedule", color: "#5a9b7d" }, // sage
  Q3: { k: "C", label: "delegate", color: "#c2a15c" }, // muted gold
  Q4: { k: "D", label: "eliminate", color: "#9aa1a9" }, // grey
};
const cls = (t: Task) => CLASS[quadrant(t)];

function esc(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

function zoneOf(config: Config): string | undefined {
  return !config.timezone || config.timezone === "system" ? undefined : config.timezone;
}
function toDT(iso: string, config: Config): DateTime {
  const z = zoneOf(config);
  const d = DateTime.fromISO(iso);
  return z ? d.setZone(z) : d;
}

function progressPct(t: Task, nowISO: string): number | undefined {
  if (!t.estMin) return undefined;
  return Math.min(100, Math.round((taskGrossMin(t, nowISO) / t.estMin) * 100));
}

function deadlineHtml(t: Task, nowMs: number, config: Config): string {
  if (!t.deadline) return "";
  const z = zoneOf(config);
  const dl = DateTime.fromISO(t.deadline, z ? { zone: z } : {}).endOf("day").toMillis();
  const days = (dl - nowMs) / 86400000;
  const overdue = t.status !== "done" && days < 0;
  const urgent = t.status !== "done" && days >= 0 && days <= 2;
  const icon = overdue ? "⚠️" : urgent ? "⏰" : "📅";
  const kind = overdue ? "overdue" : urgent ? "due" : "sched";
  return `<span class="dl ${kind}">${icon} ${esc(t.deadline)}</span>`;
}

// ---- interactive importance × urgency scatter (ECharts via CDN) ----

// Embed a JS data literal safely inside a <script> (guard against </script>).
function jsonInline(v: unknown): string {
  return JSON.stringify(v).replace(/</g, "\\u003c").replace(/-->/g, "--\\u003e");
}

function scatter(p: Projection, project?: string): string {
  const pts: { title: string; u: number; i: number; k: string; color: string; project: string }[] = [];
  for (const id of p.order) {
    const t = p.tasks.get(id)!;
    if (project && t.project !== project) continue;
    if (t.status === "done") continue;
    const c = cls(t);
    pts.push({ title: t.title, u: t.urgency, i: t.importance, k: c.k, color: c.color, project: t.project ?? "" });
  }
  if (pts.length === 0) return "";

  return `
  <section class="panel">
    <h2>Priority map · importance × urgency</h2>
    <p class="sub">One dot per open task by importance (y) and urgency (x). Hover for details; drag to zoom.</p>
    <div id="scatter" class="chart"></div>
    <script>
    (function(){
      var pts = ${jsonInline(pts)};
      var el = document.getElementById('scatter');
      if(!el || typeof echarts === 'undefined') return;
      var dark = matchMedia('(prefers-color-scheme: dark)').matches;
      var fg = dark ? '#a0a4ab' : '#60646c', line = dark ? '#26282b' : '#e6e8eb';
      var C = { A:'#c96a6a', B:'#5a9b7d', C:'#c2a15c', D:'#9aa1a9' };
      var chart = echarts.init(el, null, { renderer:'svg' });
      // Centre the plot: map the 1–5 scores to a signed −2…2 scale (3 → 0) so
      // the axes cross at the middle. Tick labels are mapped back to 1–5.
      var M = 2.25; // axis extent
      var lbl = function(v){ return String(Math.round(v) + 3); };
      var data = pts.map(function(pt, idx){
        var j = (((idx % 3) - 1) * 0.14);
        return { value:[(pt.u - 3) + j, (pt.i - 3) - j], pt:pt, itemStyle:{ color:pt.color, borderColor:dark?'#18191b':'#fff', borderWidth:1.5 } };
      });
      var band = function(name, col, x0, y0, x1, y1, pos){
        return [{ name:name, xAxis:x0, yAxis:y0, itemStyle:{ color:col, opacity:0.08 }, label:{ show:true, color:col, fontWeight:700, position:pos, fontSize:11 } }, { xAxis:x1, yAxis:y1 }];
      };
      chart.setOption({
        grid:{ left:60, right:26, top:22, bottom:52 },
        tooltip:{ trigger:'item', formatter:function(o){ var q=o.data.pt; return '<b>'+q.title+'</b><br/>importance '+q.i+' · urgency '+q.u+' · class '+q.k+(q.project?'<br/>project '+q.project:''); } },
        xAxis:{ name:'Urgency →', nameLocation:'middle', nameGap:30, min:-M, max:M, interval:1, axisLabel:{ color:fg, formatter:lbl }, nameTextStyle:{ color:fg, fontWeight:600 }, splitLine:{ lineStyle:{ color:line } } },
        yAxis:{ name:'Importance →', nameLocation:'middle', nameGap:34, min:-M, max:M, interval:1, axisLabel:{ color:fg, formatter:lbl }, nameTextStyle:{ color:fg, fontWeight:600 }, splitLine:{ lineStyle:{ color:line } } },
        series:[{
          type:'scatter', symbolSize:20, data:data, emphasis:{ scale:1.35 },
          markArea:{ silent:true, data:[
            band('B · schedule', C.B, -M, 0, 0, M, 'insideTopLeft'),
            band('A · do first', C.A, 0, 0, M, M, 'insideTopRight'),
            band('D · eliminate', C.D, -M, -M, 0, 0, 'insideBottomLeft'),
            band('C · delegate', C.C, 0, -M, M, 0, 'insideBottomRight')
          ] },
          // dividing axes crossing at the centre (score 3 → 0)
          markLine:{ silent:true, symbol:'none', label:{ show:false }, lineStyle:{ color:fg, width:1.25, opacity:0.55 }, data:[ { xAxis:0 }, { yAxis:0 } ] }
        }]
      });
      window.addEventListener('resize', function(){ chart.resize(); });
    })();
    </script>
  </section>`;
}

// ---- kanban ----

function kanbanCard(t: Task, nowISO: string, nowMs: number, config: Config, showProject: boolean): string {
  const c = cls(t);
  const pct = progressPct(t, nowISO);
  const bar =
    pct !== undefined && t.status !== "done"
      ? `<div class="bar"><span style="width:${pct}%;background:${c.color}"></span></div><span class="pct">${pct}%</span>`
      : "";
  const proj = showProject && t.project ? `<span class="proj">${esc(t.project)}</span>` : "";
  return `
      <div class="card" style="--c:${c.color}">
        <div class="card-top"><span class="badge" title="${c.k} · ${c.label}">${c.k}</span><code>${esc(t.id)}</code></div>
        <div class="ct">${esc(t.title)}</div>
        <div class="meta"><span class="score">i${t.importance}·u${t.urgency}</span>${proj}${deadlineHtml(t, nowMs, config)}</div>
        ${bar ? `<div class="barrow">${bar}</div>` : ""}
      </div>`;
}

function kanban(p: Projection, nowISO: string, nowMs: number, config: Config, project?: string): string {
  const cols = board(p, project);
  const shown = COLS.filter((c) => ["todo", "doing", "done"].includes(c) || cols[c].length > 0);
  const columns = shown
    .map((col) => {
      const cards = cols[col].map((it) => kanbanCard(p.tasks.get(it.id)!, nowISO, nowMs, config, !project)).join("");
      return `
    <div class="col">
      <h3>${COL_TITLES[col]} <span class="count">${cols[col].length}</span></h3>
      ${cards || '<div class="empty">—</div>'}
    </div>`;
    })
    .join("");
  return `<section class="panel"><h2>Board</h2><div class="kanban">${columns}</div></section>`;
}

// ---- project rollup ----

function rollup(p: Projection, nowISO: string, project?: string): string {
  const rows = new Map<string, { est: number; logged: number }>();
  let anyEst = false;
  for (const id of p.order) {
    const t = p.tasks.get(id)!;
    if (project && t.project !== project) continue;
    const key = t.project ?? "(none)";
    const r = rows.get(key) ?? { est: 0, logged: 0 };
    if (t.estMin) (r.est += t.estMin), (anyEst = true);
    r.logged += taskGrossMin(t, nowISO);
    rows.set(key, r);
  }
  if (rows.size === 0 || !anyEst) return "";
  const entries = [...rows.entries()].sort((a, b) => b[1].est - a[1].est);
  const row = (label: string, est: number, logged: number, bold = false) => {
    const pct = est > 0 ? Math.min(100, Math.round((logged / est) * 100)) : 0;
    const rem = Math.max(0, est - logged);
    return `<tr${bold ? ' class="total"' : ""}><td>${esc(label)}</td><td>${est ? formatMin(est) : "—"}</td><td>${formatMin(logged)}</td><td>${est ? formatMin(rem) : "—"}</td><td><div class="bar"><span style="width:${pct}%"></span></div> ${pct}%</td></tr>`;
  };
  let est = 0,
    logged = 0;
  const body = entries.map(([k, v]) => ((est += v.est), (logged += v.logged), row(k, v.est, v.logged))).join("");
  const total = entries.length > 1 ? row("all", est, logged, true) : "";
  return `<section class="panel"><h2>Project rollup</h2><table class="tbl"><thead><tr><th>Project</th><th>Est</th><th>Logged</th><th>Rem</th><th>Progress</th></tr></thead><tbody>${body}${total}</tbody></table></section>`;
}

// ---- Work Breakdown calendar (Gantt) ----

// The rolling 3-week window (last · this · next) used to scope the timeline.
function threeWeek(nowISO: string, config: Config): { start: number; end: number }[] {
  const cur = toDT(nowISO, config).startOf("week");
  const mk = (d: DateTime) => ({ start: d.toMillis(), end: d.plus({ weeks: 1 }).toMillis() });
  return [mk(cur.minus({ weeks: 1 })), mk(cur), mk(cur.plus({ weeks: 1 }))];
}

/** Format an epoch instant for the Gantt tooltip. */
function fmtInstant(ms: number, config: Config): string {
  return toDT(new Date(ms).toISOString(), config).toFormat("LLL d, HH:mm");
}

// The Work Breakdown as a calendar timeline (ECharts Gantt): each task is a row
// in WBS order (children indented), work spans are bars over real calendar
// dates, deadlines are diamonds, and a dashed line marks "today".
function gantt(p: Projection, config: Config, nowISO: string, project?: string): string {
  const weeks = threeWeek(nowISO, config);
  const nowMs = Date.parse(nowISO);
  const lo = weeks[0].start,
    hi = weeks[2].end;
  const inScope = new Set<string>();
  for (const id of p.order) {
    const t = p.tasks.get(id)!;
    if (project && t.project !== project) continue;
    const logged = collectIntervals([t], nowISO, lo, hi).length > 0;
    if (t.status !== "done" || logged) inScope.add(id);
  }
  if (inScope.size === 0) return "";
  for (const id of [...inScope]) {
    let cur = p.tasks.get(id)?.parent;
    while (cur && p.tasks.has(cur) && !inScope.has(cur)) {
      inScope.add(cur);
      cur = p.tasks.get(cur)?.parent;
    }
  }
  // Row order: DFS (roots then children), tracking depth for indentation.
  const children = new Map<string, string[]>();
  const roots: string[] = [];
  for (const id of p.order) {
    if (!inScope.has(id)) continue;
    const t = p.tasks.get(id)!;
    if (t.parent && inScope.has(t.parent)) (children.get(t.parent) ?? children.set(t.parent, []).get(t.parent)!).push(id);
    else roots.push(id);
  }
  const order: { id: string; depth: number }[] = [];
  const walk = (id: string, depth: number) => {
    order.push({ id, depth });
    for (const c of children.get(id) ?? []) walk(c, depth + 1);
  };
  for (const r of roots) walk(r, 0);

  const z = zoneOf(config);
  const labels: string[] = [];
  const spans: { value: [number, number, number]; itemStyle: { color: string; opacity: number; borderRadius?: number }; info: string }[] = [];
  const deadlines: { value: [number, number]; itemStyle: { color: string }; info: string }[] = [];
  let minMs = lo,
    maxMs = hi;
  order.forEach(({ id, depth }, row) => {
    const t = p.tasks.get(id)!;
    const c = cls(t);
    labels.push("  ".repeat(depth) + (depth ? "└ " : "") + t.id);
    for (const s of t.spans) {
      const start = Date.parse(s.start);
      const end = s.end ? Date.parse(s.end) : nowMs;
      if (end <= start) continue;
      minMs = Math.min(minMs, start);
      maxMs = Math.max(maxMs, end);
      spans.push({
        value: [row, start, end],
        itemStyle: { color: c.color, opacity: 0.85 },
        info: `${esc(t.title)}<br/>${fmtInstant(start, config)} → ${fmtInstant(end, config)} · ${formatMin((end - start) / 60000)}`,
      });
    }
    if (t.deadline && t.status !== "done") {
      const dms = DateTime.fromISO(t.deadline, z ? { zone: z } : {}).endOf("day").toMillis();
      minMs = Math.min(minMs, dms);
      maxMs = Math.max(maxMs, dms);
      deadlines.push({ value: [dms, row], itemStyle: { color: dms < nowMs ? "#c96a6a" : "#c2a15c" }, info: `${esc(t.id)} · deadline ${t.deadline}` });
    }
  });
  const pad = 12 * 3600 * 1000;
  const G = { labels, spans, deadlines, now: nowMs, xmin: minMs - pad, xmax: maxMs + pad };
  const height = Math.max(200, order.length * 30 + 96);

  return `
  <section class="panel">
    <h2>Work Breakdown <span class="sub">· calendar timeline</span></h2>
    <p class="sub">Each row is a task (children indented); bars are logged work over calendar time. ◆ = deadline · dashed line = today · drag the slider to pan.</p>
    <div id="gantt" style="width:100%;height:${height}px"></div>
    <script>
    (function(){
      var G = ${jsonInline(G)};
      var el = document.getElementById('gantt');
      if(!el || typeof echarts === 'undefined') return;
      var dark = matchMedia('(prefers-color-scheme: dark)').matches;
      var fg = dark ? '#9a9a95' : '#6b6b66', line = dark ? '#232324' : '#ececea';
      var chart = echarts.init(el, null, { renderer:'svg' });
      function renderItem(params, api){
        var ci = api.value(0);
        var s = api.coord([api.value(1), ci]);
        var e = api.coord([api.value(2), ci]);
        var h = api.size([0,1])[1] * 0.52;
        var rect = echarts.graphic.clipRectByRect(
          { x:s[0], y:s[1]-h/2, width:Math.max(3, e[0]-s[0]), height:h },
          { x:params.coordSys.x, y:params.coordSys.y, width:params.coordSys.width, height:params.coordSys.height }
        );
        return rect && { type:'rect', shape:Object.assign(rect,{ r:3 }), style:api.style() };
      }
      chart.setOption({
        grid:{ left:158, right:26, top:14, bottom:60 },
        tooltip:{ trigger:'item', formatter:function(p){ return (p.data && p.data.info) || ''; } },
        xAxis:{ type:'time', min:G.xmin, max:G.xmax, axisLabel:{ color:fg, hideOverlap:true }, axisLine:{ lineStyle:{ color:line } }, splitLine:{ show:true, lineStyle:{ color:line } } },
        yAxis:{ type:'category', data:G.labels, inverse:true, axisLabel:{ color:fg, fontSize:11, fontFamily:'ui-monospace,monospace' }, axisTick:{ show:false }, axisLine:{ show:false }, splitLine:{ show:true, lineStyle:{ color:line } } },
        dataZoom:[{ type:'slider', xAxisIndex:0, height:16, bottom:26 }, { type:'inside', xAxisIndex:0 }],
        series:[
          { type:'custom', renderItem:renderItem, encode:{ x:[1,2], y:0 }, data:G.spans,
            markLine:{ silent:true, symbol:'none', lineStyle:{ color:'#c96a6a', type:'dashed', width:1 }, data:[{ xAxis:G.now, label:{ formatter:'today', color:'#c96a6a', fontSize:10, position:'insideEndTop' } }] } },
          { type:'scatter', symbol:'diamond', symbolSize:12, encode:{ x:0, y:1 }, data:G.deadlines, z:5 }
        ]
      });
      window.addEventListener('resize', function(){ chart.resize(); });
    })();
    </script>
  </section>`;
}

// ---- metrics, per-axis splits, sprint ----

/** Gross minutes on a task within [lo, hi). */
function grossIn(t: Task, nowISO: string, lo: number, hi: number): number {
  let s = 0;
  for (const iv of collectIntervals([t], nowISO, lo, hi)) s += (iv.end - iv.start) / 60000;
  return s;
}

function metricsSection(p: Projection, config: Config, nowISO: string): string {
  const today = report(p, config, nowISO, { window: "today", by: "project" });
  const week = report(p, config, nowISO, { window: "week", by: "project" });
  if (week.grossMin === 0 && today.grossMin === 0) {
    return `<section class="panel"><h2>Metrics</h2><p class="sub">No time logged yet — start a task and it'll show up here.</p></section>`;
  }
  const wq = report(p, config, nowISO, { window: "week", by: "quadrant" });
  const qm = new Map(wq.distribution);
  const share = (q: string) => (wq.grossMin > 0 ? Math.round(((qm.get(q) ?? 0) / wq.grossMin) * 100) : 0);
  const stat = (label: string, val: string) => `<div class="stat"><div class="sv">${val}</div><div class="sl">${label}</div></div>`;
  const projRows = week.distribution
    .map(([k, v]) => {
      const pct = Math.round((v / week.grossMin) * 100);
      return `<tr><td>${esc(k)}</td><td>${formatMin(v)}</td><td><div class="bar"><span style="width:${pct}%"></span></div> ${pct}%</td></tr>`;
    })
    .join("");
  return `<section class="panel"><h2>Metrics <span class="sub">· ${esc(week.win.label)}</span></h2>
    <div class="stats">
      ${stat("Today", formatMin(today.netMin))}
      ${stat("Week · net", formatMin(week.netMin))}
      ${stat("Week · gross", formatMin(week.grossMin))}
      ${stat("Multitask", "×" + week.multitaskFactor.toFixed(2))}
      ${stat("Interruptions", String(week.interruptions))}
    </div>
    <div class="mix">
      <span class="mi" style="--c:#5a9b7d">valuable ${share("Q2")}%</span>
      <span class="mi" style="--c:#c96a6a">firefighting ${share("Q1")}%</span>
      <span class="mi" style="--c:#c2a15c">interruptions ${share("Q3")}%</span>
      <span class="mi" style="--c:#9aa1a9">low-value ${share("Q4")}%</span>
    </div>
    <table class="tbl"><thead><tr><th>Project</th><th>Time</th><th>Share</th></tr></thead><tbody>${projRows}</tbody></table>
  </section>`;
}

function axisSection(p: Projection, config: Config, nowISO: string, axis: "importance" | "urgency", project?: string): string {
  const win = windowFor("week", p, nowISO, config);
  const m = new Map<number, number>();
  let total = 0;
  for (const id of p.order) {
    const t = p.tasks.get(id)!;
    if (project && t.project !== project) continue;
    const g = grossIn(t, nowISO, win.start, win.end);
    if (g <= 0) continue;
    const k = axis === "importance" ? t.importance : t.urgency;
    m.set(k, (m.get(k) ?? 0) + g);
    total += g;
  }
  if (total <= 0) return "";
  const rows: string[] = [];
  for (let s = 5; s >= 1; s--) {
    const v = m.get(s) ?? 0;
    if (v <= 0) continue;
    const pct = Math.round((v / total) * 100);
    rows.push(`<tr><td>${s}</td><td>${formatMin(v)}</td><td><div class="bar"><span style="width:${pct}%"></span></div> ${pct}%</td></tr>`);
  }
  const title = axis === "importance" ? "Time by importance" : "Time by urgency";
  return `<section class="panel"><h2>${title} <span class="sub">· ${esc(win.label)}</span></h2>
    <table class="tbl"><thead><tr><th>Level</th><th>Time</th><th>Share</th></tr></thead><tbody>${rows.join("")}</tbody></table></section>`;
}

function sprintSection(p: Projection, config: Config, nowISO: string): string {
  const open = [...p.periods.values()].find((pr) => pr.open);
  if (!open) return "";
  const r = report(p, config, nowISO, { window: "sprint", by: "project" });
  if (!r.onTrack) return "";
  const { remainingMin, capacityMin, verdict } = r.onTrack;
  const pct = capacityMin > 0 ? Math.min(100, Math.round((remainingMin / capacityMin) * 100)) : 0;
  const risk = verdict !== "on track";
  return `<section class="panel"><h2>Sprint <span class="sub">· ${esc(open.id)} (${open.start} → ${open.end})</span></h2>
    <p class="sub">${formatMin(remainingMin)} remaining vs ${formatMin(capacityMin)} capacity</p>
    <div class="barrow"><div class="bar"><span style="width:${pct}%;background:${risk ? "#c96a6a" : "#5a9b7d"}"></span></div><span class="pct">${esc(verdict)}</span></div>
  </section>`;
}

// ---- page ----

export function boardHtml(p: Projection, config: Config, nowISO: string, project?: string): string {
  const nowMs = Date.parse(nowISO);
  const total = p.order.filter((id) => !project || p.tasks.get(id)!.project === project).length;
  const doing = [...p.tasks.values()].filter((t) => t.status === "doing" && (!project || t.project === project)).length;
  const generated = toDT(nowISO, config).toFormat("yyyy-LL-dd HH:mm");
  const legend = Object.values(CLASS)
    .map((c) => `<span class="lg"><span class="sw" style="background:${c.color}"></span>${c.k} · ${c.label}</span>`)
    .join("");

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>Tempo Board</title>
<script src="https://cdn.jsdelivr.net/npm/echarts@5.5.1/dist/echarts.min.js"></script>
<style>
/* Clean Minimalism: soft off-white ground, hairline borders, whitespace over
   rules, muted accents. Calm, focused, premium. */
:root{
  --bg:#f5f5f3;--panel:#fdfdfc;--ink:#1a1a19;--muted:#6b6b66;--faint:#9b9b95;
  --line:#ececea;--hair:#f1f1ef;--radius:14px;
}
@media (prefers-color-scheme:dark){:root{
  --bg:#0e0e0f;--panel:#161617;--ink:#f2f2f0;--muted:#9a9a95;--faint:#6a6a66;
  --line:#232324;--hair:#1d1d1e;
}}
*{box-sizing:border-box}
body{margin:0;font:14px/1.65 ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;background:var(--bg);color:var(--ink);-webkit-font-smoothing:antialiased;text-rendering:optimizeLegibility}
.wrap{max-width:1040px;margin:0 auto;padding:64px 32px 112px}
header{margin-bottom:8px}
header h1{margin:0 0 10px;font-size:26px;font-weight:600;letter-spacing:-0.02em}
.status{color:var(--muted);font-size:13.5px}
.status b{color:var(--ink);font-weight:600}
.legend{display:flex;flex-wrap:wrap;gap:20px;margin:20px 0 0;font-size:12px;color:var(--muted)}
.lg{display:inline-flex;align-items:center;gap:8px}
.sw{width:8px;height:8px;border-radius:50%;display:inline-block}
.panel{background:var(--panel);border:1px solid var(--line);border-radius:var(--radius);padding:32px 34px;margin:24px 0}
.panel h2{margin:0;font-size:12px;font-weight:600;text-transform:uppercase;letter-spacing:0.09em;color:var(--muted)}
.panel h2 .sub{text-transform:none;letter-spacing:0;font-weight:400;color:var(--faint)}
.sub{color:var(--faint);font-size:12.5px;margin:8px 0 24px;font-weight:400}
.chart{width:100%;height:440px;margin-top:8px}
.stats{display:flex;flex-wrap:wrap;gap:40px;margin:22px 0 6px}
.stat .sv{font-size:23px;font-weight:600;letter-spacing:-0.02em;font-variant-numeric:tabular-nums}
.stat .sl{font-size:11px;color:var(--faint);text-transform:uppercase;letter-spacing:0.06em;margin-top:4px}
.mix{display:flex;flex-wrap:wrap;gap:18px;margin:16px 0 4px;font-size:12.5px;color:var(--muted)}
.mix .mi{display:inline-flex;align-items:center;gap:7px}
.mix .mi::before{content:"";width:8px;height:8px;border-radius:50%;background:var(--c)}
.kanban{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:28px;margin-top:26px}
.col h3{margin:0 0 18px;font-size:11px;font-weight:600;text-transform:uppercase;letter-spacing:0.07em;color:var(--faint)}
.col .count{color:var(--faint);font-weight:400;margin-left:5px}
.card{border:1px solid var(--hair);border-radius:11px;padding:15px 16px;margin-bottom:12px;background:var(--bg)}
.card-top{display:flex;align-items:center;gap:9px;margin-bottom:6px}
.badge{background:color-mix(in srgb,var(--c,#9aa1a9) 15%,transparent);color:var(--c,#9aa1a9);font-weight:700;font-size:10.5px;width:19px;height:19px;border-radius:6px;display:inline-flex;align-items:center;justify-content:center;flex:0 0 auto}
.badge.sm{width:17px;height:17px;font-size:10px}
.card code,.node code{font-size:11px;color:var(--faint)}
.ct{font-weight:600;margin-bottom:7px;letter-spacing:-0.01em}
.meta{font-size:11.5px;color:var(--muted);display:flex;flex-wrap:wrap;gap:9px;align-items:center}
.score{font-variant-numeric:tabular-nums;font-weight:600;color:var(--ink)}
.proj{color:var(--faint)}
.dl{border-radius:6px;padding:1px 7px;font-size:11px}
.dl.overdue{background:#c96a6a1f;color:#c96a6a}
.dl.due{background:#c2a15c22;color:#a8863f}
.barrow{display:flex;align-items:center;gap:9px;margin-top:11px}
.bar{flex:1;height:5px;background:var(--hair);border-radius:4px;overflow:hidden}
.bar.mini{width:64px;flex:0 0 64px}
.bar span{display:block;height:100%;background:var(--muted)}
.pct{font-size:11px;color:var(--faint);font-variant-numeric:tabular-nums}
.empty{color:var(--faint);opacity:.6;font-size:13px}
.tbl{width:100%;border-collapse:collapse;font-size:13px;margin-top:20px}
.tbl th{text-align:left;padding:0 14px 12px;font-size:11px;font-weight:600;text-transform:uppercase;letter-spacing:0.05em;color:var(--faint)}
.tbl td{text-align:left;padding:11px 14px;border-top:1px solid var(--hair)}
.tbl th:not(:first-child),.tbl td:not(:first-child){text-align:right}
.tbl td:last-child,.tbl th:last-child{width:160px}
.tbl .total td{font-weight:700;color:var(--ink)}
.tbl .bar{display:inline-block;width:72px;vertical-align:middle}
.tree,.tree ul{list-style:none;margin:0;padding:0}
.tree{margin-top:22px}
.tree ul{margin-left:22px;padding-left:0}
.tree li{margin:9px 0}
.node{display:flex;flex-wrap:wrap;align-items:center;gap:9px}
.node .nt{font-weight:600;letter-spacing:-0.01em}
.nmeta{font-size:11.5px;color:var(--muted)}
.spark{display:inline-flex;align-items:flex-end;gap:2px;height:15px}
.spark .wk{width:5px;height:15px;background:var(--hair);border-radius:1px;display:inline-flex;align-items:flex-end}
.spark .wk span{width:100%;background:var(--faint);border-radius:1px;min-height:1px}
footer{color:var(--faint);font-size:11px;text-align:center;margin-top:40px}
</style>
</head>
<body>
<div class="wrap">
<header>
  <h1>Tempo Board${project ? ` · ${esc(project)}` : ""}</h1>
  <div class="status"><b>${total}</b> task${total === 1 ? "" : "s"} · <b>${doing}</b> in progress · updated ${generated}</div>
  <div class="legend">${legend}</div>
</header>
${kanban(p, nowISO, nowMs, config, project)}
${rollup(p, nowISO, project)}
${gantt(p, config, nowISO, project)}
${metricsSection(p, config, nowISO)}
${scatter(p, project)}
${axisSection(p, config, nowISO, "importance", project)}
${axisSection(p, config, nowISO, "urgency", project)}
${sprintSection(p, config, nowISO)}
<footer>Auto-generated after each change — do not edit by hand. agent-board.md holds the same data as text.</footer>
</div>
</body>
</html>
`;
}
